//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCweatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public int Weather_ID { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public Nullable<int> Prec { get; set; }
        public Nullable<int> Hum { get; set; }
        public Nullable<int> WindS { get; set; }
    
        public virtual City City { get; set; }
    }
}
